### ISSUE TITLE
Some questions about `queries`

### ISSUE THREAD

**Issue by ScienceLi1125** [Jumpat/SegAnyGAussians#35]
Thank you for your excellent work! But I have some questions about `queries` at inference stage. In the paper, `With a rendered feature map Frv for a specific view v, we generate queries for positive points and negative points by directly retrieving their corresponding features on Frv`. May I ask how can I understand these queries? And how can we generate them?

Moreover, is there any relationship between these queries at inference stage and the mask queries T_M_i at training stage?

Thanks a lot!

**Comment by Jumpat** [comment]
Hi. These queries are very similar to the so-called T_M_i, which are used to retrieve the segmentation target by feature matching.

These queries can be generated by average pooling / k-means clustering / simple retrieving from the rendered 2D feature maps or low-dimensional SAM feature maps. 

Since the linearity of the differentiable rasterization operation, the 3D features and rendered features (or low-dim SAM features) are in the same feature space, thus you can check whether a 3D Gaussian is needed through checking the feature similarity between it and a feature prototype (query).

**Comment by ScienceLi1125** [comment]
Thank you for your perfect reply! I got it!
