### ISSUE TITLE
Any webpage visualization?

### ISSUE THREAD

**Issue by wangmiaowei** [Jumpat/SegAnyGAussians#85]
Thanks for your job, since I access the cluster only by vscode remotely, which can not create the page for Glfw Error 65544: X11: The DISPLAY environment variable is missing
Glfw Error 65537: The GLFW library is not initialized
Glfw Error 65537: The GLFW library is not initialized
Glfw Error 65537: The GLFW library is not initialized
Glfw Error 65537: The GLFW library is not initialized

So any method to visualize that by just CPU when download or using web formate to present?

**Comment by yzslab** [comment]
Try this: https://github.com/yzslab/gaussian-splatting-lightning#43-load-model-trained-by-other-implementations
```bash
python viewer.py \
    SegAnyGAussians/outputs/Truck \
    --vanilla_seganygs
```

<video src="https://github.com/yzslab/gaussian-splatting-lightning/assets/564361/0b98a8ed-77d7-436d-b9f8-c5b51af5ba52"></video>

**Comment by Jumpat** [comment]
Since the SAGA GUI is implemented with Dearpygui, x11 forward is essential for visualization. However, in practice I found it hard to conduct. You can try the web GUI provided by @yzslab (Thanks for the integration! I have also used this web GUI for visualization in my research previously). Besides, you can use the Jupyter-notebook ([prompt_segmenting.ipynb](https://github.com/Jumpat/SegAnyGAussians/blob/v2/prompt_segmenting.ipynb)) for segmentation.
