### ISSUE TITLE
about downsample

### ISSUE THREAD

**Issue by Zhao-Yian** [Jumpat/SegAnyGAussians#87]
If I want to reproduce the metrics in the paper, what downsample should be set to? If it is set to 1, the memory usage is very high, but can the results be reproduced if it is set to 4/8?

**Comment by Zhao-Yian** [comment]
In addition, can you provide the results of each scene on the NVOS dataset? If convenient, can we discuss it in detail via email or WeChat?

**Comment by Jumpat** [comment]
> If I want to reproduce the metrics in the paper, what downsample should be set to? If it is set to 1, the memory usage is very high, but can the results be reproduced if it is set to 4/8?

Hi, it's okay to downsample in practice since the 3D prior can help refine the segmentation results. Downsampling does not affect too much about the final performance. However, during training, an important issue is keeping the resolution of the rendered feature map and upsample the gt feature.

I can provide the per-scene results. You can leave the e-mail address or WeChat id and I will reach out.

**Comment by Zhao-Yian** [comment]
Thank you for your answer. Thank you for providing more results. My WeChat ID is Yian_Zhao
