### ISSUE TITLE
cuda out of memory when use > 500 images

### ISSUE THREAD

**Issue by blueFeather111** [Jumpat/SegAnyGAussians#9]
when I use 550 images (size = 640 * 480) and run train_contrastive_feature.py,
no resize, downsample=1,
there is cuda out of memory error, 
does this mean there is no need to use many images? can you give some advice?
RTX 3090

**Comment by Jumpat** [comment]
Hello! This is because that the SAM-extracted masks are preloaded to GPU. According to the complexity of the scene, the masks occupies a lot of GPU memory. An intuitive way to solve this problem is to conduct frame extraction for the dataset, e.g., sampling one frame from 5 frames for training the 3D features.

**Comment by blueFeather111** [comment]
thanks, it is very kind of you.

> Hello! This is because that the SAM-extracted masks are preloaded to GPU. According to the complexity of the scene, the masks occupies a lot of GPU memory. An intuitive way to solve this problem is to conduct frame extraction for the dataset, e.g., sampling one frame from 5 frames for training the 3D features.
